#!/usr/bin/env node
/**
 * Build the MCPB bundle (`.mcpb`) for single-click install in Claude Desktop.
 *
 *   node scripts/build-mcpb.mjs                build/<name>-<version>.mcpb (full: bundle + deps + pack)
 *   node scripts/build-mcpb.mjs --no-pack      stage build/mcpb/ (bundle + deps) but skip `mcpb pack`
 *   node scripts/build-mcpb.mjs --no-install   only esbuild the entry point into build/mcpb/server/
 *                                              (the fast path the unit test uses; externalised
 *                                              Playwright then resolves against this repo's node_modules)
 *
 * Layout produced in build/mcpb/ (the MCPB "Node.js" layout from the spec):
 *
 *   manifest.json          copied verbatim from the repo root
 *   server/index.js        the whole MCP server bundled into one ESM file by esbuild
 *   node_modules/          Playwright only (everything else is bundled into server/index.js)
 *   package.json           {"type":"module"} + the pinned Playwright version
 *   icon.png, LICENSE      if present
 *
 * Playwright is kept external and shipped as a real, flat node_modules tree because it spawns
 * its own CLI (`playwright install chromium`) at first login and cannot be bundled. The Chromium
 * binary itself (~150 MB) is NOT in the bundle; it is downloaded once on the user's machine.
 */
import * as esbuild from "esbuild";
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const stage = join(root, "build", "mcpb");
const args = new Set(process.argv.slice(2));
const doInstall = !args.has("--no-install");
const doPack = doInstall && !args.has("--no-pack");

const log = (m) => process.stderr.write(`build-mcpb: ${m}\n`);
const die = (m) => {
  log(`ERROR: ${m}`);
  process.exit(1);
};

// ---------------------------------------------------------------- sanity checks
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const manifestPath = join(root, "manifest.json");
if (!existsSync(manifestPath)) die("manifest.json is missing at the repo root");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));

if (manifest.version !== pkg.version) {
  die(`version drift: manifest.json ${manifest.version} != package.json ${pkg.version} (bump both, and src/version.ts)`);
}
const pwPkgPath = join(root, "node_modules", "playwright", "package.json");
if (!existsSync(pwPkgPath)) die("node_modules/playwright not found — run the install first (pnpm install)");
const pwVersion = JSON.parse(readFileSync(pwPkgPath, "utf8")).version;

// ---------------------------------------------------------------- clean + bundle
rmSync(stage, { recursive: true, force: true });
mkdirSync(join(stage, "server"), { recursive: true });

log(`esbuild: bundling src/mcp/run.ts -> server/index.js (Playwright ${pwVersion} external)`);
const result = await esbuild.build({
  entryPoints: [join(root, "src", "mcp", "run.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  outfile: join(stage, "server", "index.js"),
  // Playwright cannot be bundled (spawns binaries, has native deps); everything else is inlined.
  external: ["playwright", "playwright-core", "fsevents", "electron", "chromium-bidi"],
  // Give bundled CJS deps a working `require`/`__dirname` in an ESM output file.
  banner: {
    js: [
      "import { createRequire as __mcpbCreateRequire } from 'node:module';",
      "import { fileURLToPath as __mcpbFileURLToPath } from 'node:url';",
      "import { dirname as __mcpbDirname } from 'node:path';",
      "const require = __mcpbCreateRequire(import.meta.url);",
      "const __filename = __mcpbFileURLToPath(import.meta.url);",
      "const __dirname = __mcpbDirname(__filename);",
    ].join("\n"),
  },
  metafile: true,
  logLevel: "warning",
});
if (result.errors.length) die(`esbuild reported ${result.errors.length} error(s)`);

// ---------------------------------------------------------------- static files
writeFileSync(
  join(stage, "package.json"),
  JSON.stringify(
    {
      name: `${pkg.name}-bundle`,
      version: pkg.version,
      private: true,
      type: "module",
      description: "Packaged MCPB bundle — generated by scripts/build-mcpb.mjs, do not edit.",
      dependencies: { playwright: pwVersion },
    },
    null,
    2,
  ) + "\n",
);
cpSync(manifestPath, join(stage, "manifest.json"));
for (const f of ["icon.png", "LICENSE", ".mcpbignore"]) {
  if (existsSync(join(root, f))) cpSync(join(root, f), join(stage, f));
}

if (!doInstall) {
  log(`staged (bundle only) at ${stage}`);
  log("skipped: Playwright install + mcpb pack (--no-install)");
  process.exit(0);
}

// ---------------------------------------------------------------- Playwright deps
log(`npm install --omit=dev playwright@${pwVersion} (browser download skipped)`);
const npm = spawnSync(
  process.platform === "win32" ? "npm.cmd" : "npm",
  ["install", "--omit=dev", "--no-package-lock", "--no-audit", "--no-fund", "--loglevel=error"],
  {
    cwd: stage,
    stdio: ["ignore", "inherit", "inherit"],
    env: { ...process.env, PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1", npm_config_loglevel: "error" },
    shell: process.platform === "win32",
  },
);
if (npm.status !== 0) die(`npm install in the staging dir failed (exit ${npm.status})`);

// Guard: the bundle must not carry a Chromium download or the repo's dev deps.
for (const leak of ["node_modules/.cache", "node_modules/typescript", "node_modules/vitest", "node_modules/esbuild"]) {
  if (existsSync(join(stage, leak))) die(`unexpected content in the bundle: ${leak}`);
}

// ---------------------------------------------------------------- validate + pack
const mcpbBin = join(root, "node_modules", ".bin", process.platform === "win32" ? "mcpb.cmd" : "mcpb");
const mcpb = (subArgs) =>
  spawnSync(existsSync(mcpbBin) ? mcpbBin : "mcpb", subArgs, { cwd: root, stdio: ["ignore", "inherit", "inherit"], shell: process.platform === "win32" });

log("mcpb validate");
if (mcpb(["validate", join(stage, "manifest.json")]).status !== 0) die("mcpb validate failed");

if (!doPack) {
  log(`staged (validated, not packed) at ${stage}`);
  process.exit(0);
}

mkdirSync(join(root, "build"), { recursive: true });
const outFile = join(root, "build", `${pkg.name}-${pkg.version}.mcpb`);
rmSync(outFile, { force: true });
log(`mcpb pack -> ${outFile}`);
if (mcpb(["pack", stage, outFile]).status !== 0) die("mcpb pack failed");

const mb = (statSync(outFile).size / 1024 / 1024).toFixed(1);
log(`done: ${outFile} (${mb} MB)`);
log("install it in Claude Desktop: double-click, drag onto the window, or Settings > Extensions > Advanced > Install Extension");
